### PR TITLE
Some fixes for Debian

### LINKED ISSUE #228: string_view needs c++-17
Hello,

I am packaging GenomicsDB into Debian; I had to make the enclosed change ad string_view needs C++-17, not -14.

Cheers,

Pierre

[string_view_needs_cxx17.txt](https://github.com/GenomicsDB/GenomicsDB/files/9543545/string_view_needs_cxx17.txt)

### PR DESCRIPTION
**Pull request by nalinigans**
This fixes #228 and #229.  I am still thinking about how to handle the fmt issue (#230) as we mostly just use the header from spdlog. And @mlathara, I will leave #231 to you. One of the dependabot's PRs also got pulled into this branch.

### CODE REVIEW

File: src/main/java/org/genomicsdb/importer/extensions/CallSetMapExtensions.java [hunk 1]
```diff
@@ -221,39 +224,47 @@ default GenomicsDBCallsetsMapProto.CallsetMappingPB generateSortedCallSetMap(
...
+            throws JsonFormat.ParseException {
         String existingCallsetsJSON = GenomicsDBUtils.readEntireFile(callsetMapJSONFilePath);
         GenomicsDBCallsetsMapProto.CallsetMappingPB.Builder callsetMapBuilder =
                 newCallsetMapPB.toBuilder();
         checkDuplicateCallsetsForIncrementalImport(existingCallsetsJSON, inputSampleNameToPath);
-        merge(existingCallsetsJSON, callsetMapBuilder);
+        try {
+          new JsonFormat().merge(new ByteArrayInputStream(existingCallsetsJSON.getBytes()), callsetMapBuilder);
+        } catch (IOException e) {
+          throw new GenomicsDBException(String.format("Could not merge incremental import's callsets with existing callsets : %s", e.getMessage()));
```
Comment (webberlh) [inline src/main/java/org/genomicsdb/importer/extensions/CallSetMapExtensions.java:241]: Should the `GenomicsDBException` be added to the javadoc? I see that `checkDuplicateCallsetsForIncrementalImport` seems to follow that convention, but if that's not common in the library as a whole this comment can be ignored.

Comment (nalinigans) [reply src/main/java/org/genomicsdb/importer/extensions/CallSetMapExtensions.java:241]: Actually, even if it is not common in the library as a whole, we need to clean up javadoc as we go. So, yes, I will add the throws clause to javadoc. Thanks.

File: src/main/java/org/genomicsdb/importer/extensions/CallSetMapExtensions.java [hunk 2]
```diff
@@ -1,12 +1,15 @@
 package org.genomicsdb.importer.extensions;
 
+import com.googlecode.protobuf.format.JsonFormat;
```
Comment (mlathara) [inline src/main/java/org/genomicsdb/importer/extensions/CallSetMapExtensions.java:3]: There's an older import referencing this that can be removed
```
import static com.googlecode.protobuf.format.JsonFormat.*;
```

File: src/main/java/org/genomicsdb/importer/extensions/CallSetMapExtensions.java (hunk 1 above)
Comment (nalinigans) [reply src/main/java/org/genomicsdb/importer/extensions/CallSetMapExtensions.java:241]: Looks like `GenomicsDBException extends RuntimeException` which means a throws clause is not required in the javadoc. However, should we have a throws clause for all thrown `GenomicsDBException` for consistency sake? gatk does not have to explicitly look for GenomicsDBException as it is a RuntimeException, but if we start having a throws clause, it may be confusing to the gatk authors. What are your thoughts, @mlathara? Leave it as is?

Comment (mlathara) [reply src/main/java/org/genomicsdb/importer/extensions/CallSetMapExtensions.java:239]: I think I may have mistakenly added `@throws GenomicsDBException` to:
importer/GenomicsDBImporter.java
importer/extensions/CallSetMapExtensions.java

If we remove those two instances, the rest is consistent in that they don't add that to the javadoc. My vote would be to do that.

**Review by mlathara — APPROVED** [review]
looks good
